#!/bin/bash

git config user.email "youngjin988@gmail.com"
git config user.name "yogjin"

git config credential.helper store
git config --global credential.helper 'cache --timeout 7200'

exit 0
#chmod 755 set_ForGit 으로 실행권한을 주고 실행한다.